"""Create initial tables

Revision ID: f166574aaf0d
Revises: 
Create Date: 2025-07-14 17:27:18.115129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f166574aaf0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paintings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_filenames', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paintings_id'), 'paintings', ['id'], unique=False)
    op.create_index(op.f('ix_paintings_title'), 'paintings', ['title'], unique=False)
    op.create_table('usersessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersessions_id'), 'usersessions', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('painting_id', sa.Integer(), nullable=False),
    sa.Column('user_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['painting_id'], ['paintings.id'], ),
    sa.ForeignKeyConstraint(['user_session_id'], ['usersessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_session_id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_usersessions_id'), table_name='usersessions')
    op.drop_table('usersessions')
    op.drop_index(op.f('ix_paintings_title'), table_name='paintings')
    op.drop_index(op.f('ix_paintings_id'), table_name='paintings')
    op.drop_table('paintings')
    # ### end Alembic commands ###
